In [1]:
# import requests
# import zipfile
# import io
import pandas as pd
import sqlite3
# from google.cloud import bigquery
# data from 1992 to 2018

In [2]:
# # url for zipped data
# url = 'https://www.fs.usda.gov/rds/archive/products/RDS-2013-0009.6/RDS-2013-0009.6_SQLITE.zip'
# # get zipped data
# response = requests.get(url, stream=True)
# z = zipfile.ZipFile(io.BytesIO(response.content))

In [3]:
# # extract necessary files
# z.extract('Data/FPA_FOD_20221014.sqlite')
# z.extract('Data/_variable_descriptions.csv')

In [4]:
# original pandas_gbq query
long_sql_aq = """
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.co_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.hap_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.no2_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.o3_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.pressure_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.rh_and_dp_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.so2_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.temperature_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.voc_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,event_type,observation_count,
arithmetic_mean,first_max_value,first_max_hour,aqi,county_name,city_name
FROM `bigquery-public-data.epa_historical_air_quality.wind_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31'
"""

long_sql_pt = """
SELECT  
    measurement_year,
    latitude,longitude,elevation,
    trees_per_acre_unadjusted,
    water_on_plot_code_name,
    species_common_name,species_group_code_name,
    total_height,
    current_diameter,
    tree_status_code_name,
    invasive_sampling_status_code_name,
FROM `bigquery-public-data.usfs_fia.plot_tree`
WHERE plot_state_code = 6
"""

In [2]:
sql_aq = """
SELECT *
FROM `california_air_trees_fires.epa_aq_ca1`
"""

sql_pt = """
SELECT *
FROM `california_air_trees_fires.usfs_fia_pt_ca1`
"""

In [12]:
# pandas gbq will auth with google account first, rerun after
aq = pd.read_gbq(sql_aq, dialect='standard', project_id='my-ds-projects', use_bqstorage_api=True)

In [13]:
aq.head()

,poc,latitude,longitude,parameter_name,sample_duration,date_local,units_of_measure,observation_count,arithmetic_mean,county_code
0,1,37.220640,-119.155557,Calcium PM2.5 LC,24 HOUR,2009-06-03,Micrograms/cubic meter (LC),1,0.0096,019
1,5,36.781333,-119.773190,Zinc PM2.5 LC,24 HOUR,2002-12-31,Micrograms/cubic meter (LC),1,0.0083,019
2,5,36.781333,-119.773190,Zinc PM2.5 LC,24 HOUR,2002-07-07,Micrograms/cubic meter (LC),1,0.0000,019
3,11,34.100020,-117.492010,Strontium PM2.5 LC,24 HOUR,2009-01-07,Micrograms/cubic meter (LC),1,0.0000,071
4,6,35.356615,-119.062613,"1,3-Butadiene",24 HOUR,2018-01-02,Parts per billion Carbon,1,0.8000,029

In [50]:
# pandas gbq will auth with google account first, rerun after
pt = pd.read_gbq(sql_pt, dialect='standard', project_id='my-ds-projects', use_bqstorage_api=True)

In [51]:
pt.head()

,measurement_year,tree_county_code,latitude,longitude,elevation,trees_per_acre_unadjusted,water_on_plot_code_name,species_common_name,species_group_code_name,total_height,current_diameter,tree_status_code_name,invasive_sampling_status_code_name
0,1991,15,41.990555,-124.190834,300,2.678599,,Sitka spruce,Sitka spruce,72,20.4,Live tree,
1,1991,23,40.533333,-124.249725,1200,23.657600,,willow spp.,Other western hardwoods,26,4.3,Live tree,
2,1991,23,40.553890,-124.128334,100,1.661400,,eucalyptus spp.,Other western hardwoods,92,25.9,Live tree,
3,1991,23,40.577507,-124.006943,900,8.291200,,grand fir,True fir,111,11.6,Live tree,
4,1991,23,40.731670,-123.870834,500,11.183799,,Oregon ash,Other western hardwoods,56,10.0,Live tree,

In [52]:
pt.columns

Index(['measurement_year', 'tree_county_code', 'latitude', 'longitude',
       'elevation', 'trees_per_acre_unadjusted', 'water_on_plot_code_name',
       'species_common_name', 'species_group_code_name', 'total_height',
       'current_diameter', 'tree_status_code_name',
       'invasive_sampling_status_code_name'],
      dtype='object')

In [53]:
# # california plots
# # pd.read_csv('https://apps.fs.usda.gov/fia/datamart/CSV/CA_PLOT.csv')
# cap = pd.read_csv('Data/CA_PLOT.csv')

# cap_col_idx = [x-1 for x in (
#     [1]+
#     list(range(12,15))+
#     list(range(18,23))+
#     [28,54]+
#     list(range(59,64))+
#     list(range(65,70))
#     )]

# # california trees
# # pd.read_csv('https://apps.fs.usda.gov/fia/datamart/CSV/CA_TREE.csv')
# cat = pd.read_csv('Data/CA_TREE.csv',dtype={'P2A_GRM_FLG':str,'GST_PNWRS':str})

# cat_col_idx = [x-1 for x in (
#     [2,4,7]+
#     list(range(15,19))+
#     [20,21,22,24,25]+
#     list(range(145,148))
#     )]

In [54]:
# cat.columns[cat_col_idx]

In [55]:

# cap = cap[cap.columns[cap_col_idx]]
# cat = cat[cat.columns[cat_col_idx]]
# # california trees n plots merged
# capt = pd.merge(cat,cap,'left',left_on='PLT_CN',right_on='CN').drop(columns=['PLT_CN','CN'])
# capt = capt[(capt.notnull().sum() > 0)[capt.notnull().sum() > 0].index]
# # capt

In [56]:
# capt.columns

In [57]:
conn = sqlite3.connect('Data/FPA_FOD_20221014.sqlite')

In [58]:
fire = pd.read_sql('''
                    select 
                    FIRE_YEAR,
                    DISCOVERY_DATE,
                    DISCOVERY_DOY,
                    DISCOVERY_TIME,
                    NWCG_CAUSE_CLASSIFICATION,
                    NWCG_GENERAL_CAUSE,
                    FIRE_SIZE,
                    FIRE_SIZE_CLASS,
                    LATITUDE,
                    LONGITUDE,
                    COUNTY,
                    FIPS_CODE,
                    FIPS_NAME
                    from fires where STATE = :state
                    ''',conn,params={'state':'CA'})
# fire = pd.read_sql('''
#                     select FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,
#                         NWCG_CAUSE_CLASSIFICATION,NWCG_GENERAL_CAUSE,
#                         FIRE_SIZE,FIRE_SIZE_CLASS,
#                         LATITUDE,LONGITUDE
#                     from fires
#                     where STATE = :state
#                     ''',conn,params={'state':'CA'})
fire.columns = fire.columns.str.lower()

In [59]:
fire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251881 entries, 0 to 251880
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   fire_year                  251881 non-null  int64
 1   discovery_date             251881 non-null  object
 2   discovery_doy              251881 non-null  int64
 3   discovery_time             206816 non-null  object
 4   nwcg_cause_classification  251881 non-null  object
 5   nwcg_general_cause         251881 non-null  object
 6   fire_size                  251881 non-null  float64
 7   fire_size_class            251881 non-null  object
 8   latitude                   251881 non-null  float64
 9   longitude                  251881 non-null  float64
 10  county                     157156 non-null  object
 11  fips_code                  157156 non-null  object
 12  fips_name                  157156 non-null  object
dtypes: float64(3), int64(2), object(8)
memory usage: 25.0+ MB

In [60]:
fire.describe().T

,count,mean,std,min,25%,50%,75%,max
fire_year,251881.0,2006.010457,8.302032,1992.000000,1999.000000,2006.000000,2013.000000,2020.0000
discovery_doy,251881.0,200.923678,67.495270,1.000000,162.000000,201.000000,246.000000,366.0000
fire_size,251881.0,83.082573,3039.451969,0.001000,0.100000,0.200000,1.000000,589368.0000
latitude,251881.0,37.251235,2.559057,32.537406,34.661935,37.396107,39.226593,42.4175
longitude,251881.0,-120.118132,2.130694,-124.402883,-121.680684,-120.491111,-118.345556,-114.1258

In [61]:
fire

,fire_year,discovery_date,discovery_doy,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude,longitude,county,fips_code,fips_name
0,2005,2/2/2005,33,1300,Human,Power generation/transmission/distribution,0.10,A,40.036944,-121.005833,63,06063,Plumas County
1,2004,5/12/2004,133,0845,Natural,Natural,0.25,A,38.933056,-120.404444,61,06061,Placer County
2,2004,5/31/2004,152,1921,Human,Debris and open burning,0.10,A,38.984167,-120.735556,17,06017,El Dorado County
3,2004,6/28/2004,180,1600,Natural,Natural,0.10,A,38.559167,-119.913333,3,06003,Alpine County
4,2004,6/28/2004,180,1600,Natural,Natural,0.10,A,38.559167,-119.933056,3,06003,Alpine County
...,...,...,...,...,...,...,...,...,...,...,...,...,...
251876,2019,10/31/2019,304,2115,Missing data/not specified/undetermined,Missing data/not specified/undetermined,9999.00,G,34.337222,-119.053333,Ventura,06111,Ventura County
251877,2019,5/29/2019,149,1900,Missing data/not specified/undetermined,Missing data/not specified/undetermined,835.00,E,35.307500,-119.964444,San Luis Obispo,06079,San Luis Obispo County
251878,2019,6/25/2019,176,2230,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2422.00,F,37.472222,-121.249444,Stanislaus,06099,Stanislaus County
251879,2019,9/4/2019,247,1446,Missing data/not specified/undetermined,Missing data/not specified/undetermined,54608.00,G,40.053250,-120.668900,Plumas,06063,Plumas County
251880,2020,7/11/2020,193,1958,Missing data/not specified/undetermined,Missing data/not specified/undetermined,100.00,D,37.148611,-119.503056,Madera,06039,Madera County

In [62]:
# pt['lat'] = round(pt.latitude,1)
# pt['lon'] = round(pt.longitude,1)
# fire['lat'] = round(fire.latitude,1)
# fire['lon'] = round(fire.longitude,1)
pt = pt[pt['tree_county_code'].notna()].copy()
fire = fire[fire['county'].notna()].copy()
fire['county_code'] = fire.fips_code.str[2:].astype(int)
fire

,fire_year,discovery_date,discovery_doy,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude,longitude,county,fips_code,fips_name,county_code
0,2005,2/2/2005,33,1300,Human,Power generation/transmission/distribution,0.10,A,40.036944,-121.005833,63,06063,Plumas County,63
1,2004,5/12/2004,133,0845,Natural,Natural,0.25,A,38.933056,-120.404444,61,06061,Placer County,61
2,2004,5/31/2004,152,1921,Human,Debris and open burning,0.10,A,38.984167,-120.735556,17,06017,El Dorado County,17
3,2004,6/28/2004,180,1600,Natural,Natural,0.10,A,38.559167,-119.913333,3,06003,Alpine County,3
4,2004,6/28/2004,180,1600,Natural,Natural,0.10,A,38.559167,-119.933056,3,06003,Alpine County,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251876,2019,10/31/2019,304,2115,Missing data/not specified/undetermined,Missing data/not specified/undetermined,9999.00,G,34.337222,-119.053333,Ventura,06111,Ventura County,111
251877,2019,5/29/2019,149,1900,Missing data/not specified/undetermined,Missing data/not specified/undetermined,835.00,E,35.307500,-119.964444,San Luis Obispo,06079,San Luis Obispo County,79
251878,2019,6/25/2019,176,2230,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2422.00,F,37.472222,-121.249444,Stanislaus,06099,Stanislaus County,99
251879,2019,9/4/2019,247,1446,Missing data/not specified/undetermined,Missing data/not specified/undetermined,54608.00,G,40.053250,-120.668900,Plumas,06063,Plumas County,63
251880,2020,7/11/2020,193,1958,Missing data/not specified/undetermined,Missing data/not specified/undetermined,100.00,D,37.148611,-119.503056,Madera,06039,Madera County,39

In [63]:
fire.shape,pt.shape

((157156, 14), (371865, 13))

In [68]:
# fpt = pd.merge(left=fire,right=pt,how='left',left_on=['fire_year','county_code'],right_on=['measurement_year','tree_county_code'])
# fpt

In [69]:
small_fire = fire[fire.fire_year==2018]
small_fire

,fire_year,discovery_date,discovery_doy,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude,longitude,county,fips_code,fips_name,county_code
206301,2018,7/13/2018,194,1420,Natural,Natural,0.25,A,39.014444,-120.360278,017,06017,El Dorado County,17
206302,2018,7/17/2018,198,1718,Human,Recreation and ceremony,0.50,B,38.949722,-120.403889,017,06017,El Dorado County,17
206303,2018,8/1/2018,213,1847,Human,Missing data/not specified/undetermined,2.80,B,38.804444,-120.450278,017,06017,El Dorado County,17
206304,2018,8/16/2018,228,1430,Human,Recreation and ceremony,0.10,A,38.837222,-120.374167,017,06017,El Dorado County,17
206305,2018,7/1/2018,182,1400,Human,Missing data/not specified/undetermined,0.07,A,39.022500,-120.303611,017,06017,El Dorado County,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215784,2018,8/6/2018,218,1459,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2225.00,F,35.800000,-120.360000,Monterey County,06053,Monterey County,53
215785,2018,7/6/2018,187,1330,Missing data/not specified/undetermined,Missing data/not specified/undetermined,1520.00,F,33.380000,-117.430000,San Diego County,06073,San Diego County,73
215786,2018,6/28/2018,179,1945,Missing data/not specified/undetermined,Missing data/not specified/undetermined,300.00,E,40.600000,-122.900000,Trinity County,06105,Trinity County,105
215787,2018,6/9/2018,160,0945,Missing data/not specified/undetermined,Missing data/not specified/undetermined,175.00,D,34.360360,-118.554300,Los Angeles County,06037,Los Angeles County,37
215788,2018,7/31/2018,212,1934,Missing data/not specified/undetermined,Missing data/not specified/undetermined,1200.00,F,39.190000,-121.800000,Sutter County,06101,Sutter County,101

In [74]:
small_pt = pt[pt.measurement_year==2018]
small_pt = small_pt.dropna()
small_pt

,measurement_year,tree_county_code,latitude,longitude,elevation,trees_per_acre_unadjusted,water_on_plot_code_name,species_common_name,species_group_code_name,total_height,current_diameter,tree_status_code_name,invasive_sampling_status_code_name
374007,2018,109,38.232475,-120.206612,4700,0.999188,Temporary streams,white alder,Other western hardwoods,85,29.400000,Live tree,Not collecting invasive plant data
374009,2018,35,41.140858,-120.525963,5500,74.965279,Permanent streams or ponds too small to qualif...,quaking aspen,Cottonwood and aspen,22,1.800000,Live tree,Not collecting invasive plant data
374010,2018,103,40.098816,-121.641106,3500,74.965279,None - no water sources within the accessible ...,California torreya (nutmeg),Other western softwoods,13,2.100000,Live tree,Invasive plant data collected on all accessibl...
374012,2018,89,41.144722,-121.964310,5300,6.018046,None - no water sources within the accessible ...,knobcone pine,Other western softwoods,64,15.500000,Dead tree,Invasive plant data collected on all accessibl...
374013,2018,89,40.861736,-122.062080,1900,6.018046,None - no water sources within the accessible ...,California buckeye,Other western hardwoods,18,5.300000,Live tree,Invasive plant data collected on all accessibl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
396723,2018,39,37.119659,-119.775551,1500,6.018046,Temporary streams,gray or California foothill pine,Other western softwoods,63,11.200000,Live tree,Not collecting invasive plant data
396724,2018,85,37.385571,-121.461090,2300,74.965279,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,12,1.600000,Live tree,Not collecting invasive plant data
396725,2018,55,38.569389,-122.347435,1500,0.999188,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,101,35.700001,Live tree,Not collecting invasive plant data
396727,2018,11,39.213451,-122.439522,1700,6.018046,Temporary streams,gray or California foothill pine,Other western softwoods,35,5.800000,Live tree,Not collecting invasive plant data
396728,2018,53,35.889458,-121.193520,1300,6.018046,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,46,12.000000,Live tree,Not collecting invasive plant data

In [77]:
small_fpt = pd.merge(left=small_fire,right=small_pt,how='right',left_on='county_code',right_on='tree_county_code')
small_fpt

,fire_year,discovery_date,discovery_doy,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude_x,longitude_x,...,longitude_y,elevation,trees_per_acre_unadjusted,water_on_plot_code_name,species_common_name,species_group_code_name,total_height,current_diameter,tree_status_code_name,invasive_sampling_status_code_name
0,2018,7/21/2018,202,1515,Natural,Natural,5.10,B,38.257222,-119.830278,...,-120.206612,4700,0.999188,Temporary streams,white alder,Other western hardwoods,85,29.4,Live tree,Not collecting invasive plant data
1,2018,8/22/2018,234,1600,Human,Missing data/not specified/undetermined,0.25,A,38.165278,-119.877778,...,-120.206612,4700,0.999188,Temporary streams,white alder,Other western hardwoods,85,29.4,Live tree,Not collecting invasive plant data
2,2018,7/19/2018,200,1100,Human,Recreation and ceremony,0.01,A,38.341944,-119.869444,...,-120.206612,4700,0.999188,Temporary streams,white alder,Other western hardwoods,85,29.4,Live tree,Not collecting invasive plant data
3,2018,9/4/2018,247,1308,Human,Recreation and ceremony,0.10,A,38.165278,-119.877778,...,-120.206612,4700,0.999188,Temporary streams,white alder,Other western hardwoods,85,29.4,Live tree,Not collecting invasive plant data
4,2018,8/31/2018,243,1124,Human,Recreation and ceremony,0.01,A,38.239722,-119.892778,...,-120.206612,4700,0.999188,Temporary streams,white alder,Other western hardwoods,85,29.4,Live tree,Not collecting invasive plant data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2745064,2018,10/19/2018,292,1547,Missing data/not specified/undetermined,Missing data/not specified/undetermined,1.00,B,36.583236,-121.532533,...,-121.193520,1300,6.018046,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,46,12.0,Live tree,Not collecting invasive plant data
2745065,2018,11/10/2018,314,1446,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2.50,B,36.696685,-121.629552,...,-121.193520,1300,6.018046,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,46,12.0,Live tree,Not collecting invasive plant data
2745066,2018,12/31/2018,365,2134,Missing data/not specified/undetermined,Missing data/not specified/undetermined,1.00,B,36.666720,-121.628095,...,-121.193520,1300,6.018046,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,46,12.0,Live tree,Not collecting invasive plant data
2745067,2018,10/2/2018,275,1432,Missing data/not specified/undetermined,Missing data/not specified/undetermined,150.00,D,35.961080,-121.286900,...,-121.193520,1300,6.018046,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,46,12.0,Live tree,Not collecting invasive plant data
2745068,2018,8/6/2018,218,1459,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2225.00,F,35.800000,-120.360000,...,-121.193520,1300,6.018046,None - no water sources within the accessible ...,gray or California foothill pine,Other western softwoods,46,12.0,Live tree,Not collecting invasive plant data